#Main REDDIT data application
#Beware of API Throttling !!
#Working modes:
####################
# sdd - simple data downloader :
# param 1 : subredit
# param 2 : number of questions to download
# param 3 : output file path
# param 4 : generated by reddit client id
# param 5 : generated by reddit secret
# param 6 : user agent name which fullfill reddit API reuqirmenets
####################
# add advanced data downloader - TODO
####################
# c - data cleaner - TODO
# param 1 : input file path
# param 2 : output file path
####################
# Examples of use :
#
# TODO

import sys
from cleaner import clean
from downloader import download

try:
    mode = sys.argv[1]
    if mode == 'sdd': #simple data downloader
        subredit = sys.argv[2]
        amount = int(sys.argv[3])
        output = sys.argv[4]
        client_id = sys.argv[5]
        secret = sys.argv[6]
        agent = sys.argv[7]
        download(subredit,amount,output,client_id,secret,agent)
    elif mode == 'c': #clean data
        input = sys.argv[2]
        output = sys.argv[3]
        clean(input,output)
    elif mode=='add':
        print 'not supported yet'
    else:
        print 'Not supported work mode'
except:
    print 'Unspecified error occured ' , sys.exc_info()[0], ' ' , sys.exc_info()[1]
